name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  check-package:
    name: Check Package
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup pnpm
        uses: threeal/setup-pnpm-action@v1.0.0

      - name: Install Dependencies
        run: pnpm install

      - name: Check Format
        run: |
          pnpm format
          git diff --exit-code HEAD

      - name: Check Lint
        run: pnpm lint

  test-package:
    name: Test Package
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup pnpm
        uses: threeal/setup-pnpm-action@v1.0.0

      - name: Install Dependencies
        run: pnpm install

      - name: Test Package
        run: pnpm test
